const local_eng = {
    BUTTON_LANG_DE: 'Polish',
    BUTTON_LANG_EN: 'English',
    LOGIN_FAILED: 'Login failed! Please check your email or password.',
    EXCLUSION_SET: 'You\'ve set exclude. This limitation will expire ',
    INVALID_PASSWORD: 'User with the same email or password is already existed',
    USERNAME_EMAIL_REQUIRED: 'Email and password are required!',
    AMOUNT_LIMIT_SET: 'You\'ve set amount limitation. This limitation will expire',
    LOGIN_FAILED_EMAIL_NOT_VERIFIED: 'This email is not verified.',
    MAX_LOGIN_FAILURES: 'You\'ve entered the wrong login details too many times. Please contact us to resolve this.',
    PLAYER_BLOCKED: 'Your account is blocked. Please contact us to resolve this.',
    NOT_OWNED: 'Thank you for your deposit. As the bank account you used is already linked to another player account with us the money have been deposited into this other account. To access this money, please log out and then login again using Trustly and selecting the bank account you just made a deposit from.',
    EMAIL_NOT_VERIFIED: 'Until you have verified your email address - you can only login using Trustly. To verify your email address, please login using Trustly and then enter your four digit code under "My account"',
    USER_EXISTS: 'Incorrect password.',
    DONT_HAVE_TRUSTLY_ACCOUNT: 'This bank account have not been linked to any Fun88 account. Please try again or create your account by making a deposit.',
    error_support: 'Error - please contact our support!',
    INVALID_TOKEN: 'You entered incorrect code. Please try again.',
    START_REWARD_ERROR: 'To start reward circle you need verify your email.',
    WRONG_CAMPAING_CODE_ERROR: 'You\'ve seem to have entered an incorrect code. Please note that some campaigns are only applicable to a certain group of users or the campaign might have expired.',
    PLAYER_IS_BLOCKED: 'You can\'t restore password. Reason: your player is blocked.',
    navbar_component: {
        menuItems: {
            games: 'Games',
            about: 'About',
            contact_us: 'Contact us',
            sign_in: 'Sign in',
            sign_up: 'Sign up',
            faq: 'FAQ',
            deposit: 'Deposit',
        },
        dialogWindow: {
            sign_in: 'Sign in',
            email: 'Email:',
            email_placeholder: 'Email',
            cancel: 'Cancel',
            error: 'Enter a valid email.',
            password: 'Password:',
            password_placeholder: 'Password',
        },
    },
    sidebar_component: {
        my_account: 'My account',
        menuItems: {
            home: 'Home',
            game: 'Games',
            contact_us: 'Contact us',
            licenses: 'Licenses',
            faq: 'FAQ',
            about: 'About',
            deposit_money: 'Deposit money',
            withdrawal_money: 'Withdrawal money',
            finance_history: 'Finance history',
            settings: 'Responsible gaming',
            logout: 'Logout',
            sign_in: 'Sign in',
            deposit: 'Deposit',
            rewards: 'Rewards',
        },
    },
    contact_us: {
        title: 'Contact us',
        name: 'Name',
        email: 'Email',
        error: 'Enter a valid email.',
        message: 'Message',
        send_message:'Send message',
        feedback_sent: 'Your feedback is successfully sent',
    },
    footer: {
        terms_conditions: 'Terms & Conditions',
        licenses: 'Licenses',
        copyright: 'Copyright 2017',
        desktop_version: 'Desktop version',
    },
    tab_settings: {
        profile: 'Profile',
        deposit_money: 'Deposit money',
        withdrawal_money: 'Withdraw money',
        finance_history: 'Finance history',
        settings: 'Responsible gaming',
        
        settings_page: {
            set_button: 'Set',
            cancel_button: 'Cancel',
            amount_limitation: 'Wager amount limitation',
            your_amount: 'Amount',
            loss_limitatin: 'Loss limitation',
            your_loss_amount: 'Amount',
            time_limitation: 'Session time limitation',
            select_time_limitation: {
                hours: '30 minutes',
                days: '60 minutes',
                one_month: '2 hours',
                three_month: '4 hours',
                six_month: '6 months',
            },
            save_changes: 'Save changes',
            set_exclusion_block: 'Set exclusion (block account)',
            select_set_exclusion: {
                hours: '24 hours',
                days: '7 days',
                one_month: '30 days',
                six_month: '180 days',
                forever: 'Forever',
            },
            select_inactivity_timeout: {
                seconds: '30 seconds',
                five_minutes: '5 minutes',
                fifteen_minutes: '15 minutes',
                hour: '1 hour',
            },
            settings_are_saved: 'Your settings are saved!',
            success: 'Success',
            error: 'Error - please contact our support!',
            later: ' later',
            will_be_implemented: ' will be implemented ',
            amount_limit: 'Amount limitation ',
            lost_limit: 'Loss limitation ',
            time_limit: 'Time limitation ',
            error_amount: 'Amount must be between 1 and 1.000.000',
            set_wager: 'Set wager',
            set_loss: 'Set loss',
            set_session: 'Set session',
            set_exclusion: 'Set exclusion',
            set_inactivity: 'Set inactivity',
            inactivity_timeout: 'Inactivity timeout',
            set_time_period: 'Click to set time period',
            restrictions_ends: 'Restrictions ends for',
        },
        deposit_money_page: {
            country: 'Country*',
            amount: 'Amount*',
            logo_text: 'All our payments are processed securely through Trustly. Both deposits and withdrawals are instantly available!',
            countries: {
                sweden: 'Sweden',
                poland: 'Poland',
                finland: 'Finland',
                austria: 'Austria',
                belgium: 'Belgium',
                bulgaria: 'Bulgaria',
                czech_republic: 'Czech Republic',
                estonia: 'Estonia',
                germany: 'Germany',
                hungary: 'Hungary',
                ireland: 'Ireland',
                italy: 'Italy', 
                latvia: 'Latvia', 
                lithuania: 'Lithuania',
                netherlands: 'Netherland', 
                romania: 'Romania', 
                slovakia: 'Slovakia', 
                slovenia: 'Slovenia',
                spain: 'Spain',
            },
            make_deposit: 'Make deposit',
            input_validation: 'Amount must be between 5 and 1.000.000',
            currency: 'Your current currency is EUR',
            select_contry: 'Select country',
        },
        withdrawal_money_page: {
            enter_acount: 'Select account to withdrawal to',
            amount: 'Amount',
            logo_text: 'All our payments are processed securely through Trustly. Both deposits and withdrawals are instantly available!',
            withdraw_money: 'Withdraw money',
            success: 'Success',
            your_request: 'Your request was successful',
            error: 'Error - please contact our support!',
            message: 'You want to take more money than you have!',
            successful_request: 'Your request was successful', 
            ok: 'OK',
            error_amount: 'Amount must be between 1 and 1.000.000',
            select_account: 'Select account',
            are_you_sure: 'Are you sure you want to take money?',
            yes: 'Yes',
            no: 'No',
        },
        profile_page: {
            first_name: 'First name',
            last_name: 'Last name',
            date_of_birth: 'Date of birth',
            address: 'Address',
            email: 'Email',
            phone_number: 'Phone number',
            confirm_email: 'Confirm email',
            send_confirmation: 'Send me confirmation code again',
            code_from_email: 'Code from email',
            code: 'Code',
            password: 'Password',
            change_password: 'Change password',
            code_was_sent: 'Code was sent to',
            email_used: 'This email\'s already used.',
            something_wrong: 'Something went wrong. Try again later.',
            send_newsletters: 'Send newsletters',
        },
        finance_history_page: {
            search: 'Search transaction',
            all: 'All',
            deposit: 'Deposit',
            withdrawal: 'Withdrawal',
            status_accepted: 'Accepted',
            status_declined: 'Declined',
            status_pending: 'Pending',
            method_deposit: 'Deposit',
            method_withdrawal: 'Withdrawal',            
        },
    },
    sign_up: {
        sign_up: 'Sign Up',
        user_name: 'USER NAME (email)',
        email_error: 'This email is not valid.',
        error: 'This field cann\'t be empty',
        password: 'PASSWORD',
        thank_you: 'Thank you!',
        verify: 'Verify your email',
        repeat_password: 'CONFIRM PASSWORD',
        error_confirm_password: 'Password does not match the confirm password.',
        error_title: 'Error!',
        back: 'Back',
        login: {
            back: 'Back',
            login: 'Login',
            login_with_password: 'Login with password',
            password: 'Password',
            password_error: 'Password cannot be empty.',
            continue: 'Continue',
            login_with_trustly: 'Or login with Truslty',
            exclude: 'You can\'t login as used account is excluded. Exclusion expires ',
            login_with_blocked_account: 'You can\'t login as used account is blocked! Please contact our support!',
            no_trystly_account: 'No such Trustly account in our system. ',
        },
        set_email: {
            title: 'Set email',
            text: 'It seems you\'ve made a deposit using an account we haven\'t seen before. Please enter your email address. This will be our unique identifier for you. Please note, if you already have an account with us you will be able to link this new bank account to your existing Fun88 account at the next page.',
            user_name: 'User name (email)',
            email: 'Email',
            continue: 'Continue',
            i_agree: 'By clicking "Continue" I agree to Fun88\'s ',
            terms_conditions: 'Terms & Conditions ',
        },
    },
    verify: {
        thank_you: 'Thank you!',
        verify: 'Your verification is over! ',
        something: 'Something went wrong!',
        contact: ' Please contact with administrator.',
    },
    games: {
        search_game: 'Search Game',
        nothing_found: 'Nothing found!',
        sorry: 'Sorry',
        game_was_not_found: 'Game wasn\'t found',
        filters: {
            free_spins: 'Free spins',
            popular: 'Popular',
            new_releases: 'New releases',
            jackpots: 'Jackpots',
            table_games: 'Table games',
            slot_machines: 'Slot machines',
        },
        title: 'Games',
    },
    main_page: {
        main_info: {
            header: {
                first: 'Welcome to ',
                second: 'Fun88!',
            },
            button: 'Make a deposit and start winning',
            we_like: 'We like:',
            firstList: {
                header1: 'Speed,',
                text1: ' which is why all our withdrawals are paid out instant.',
                // subtitle: {
                //     first: 'No need setup a username and password',
                //     second: 'No need to login to play, just deposit and play!',
                // },
                header2: 'Simple,',
                text2: ' which is why you don\'t need to sign up to play, just make a deposit at you\'re all set',
                header3: 'Free,',
                text3: ' 10 freespins just for signing up on our Player\'s Circle rewards program!',
                header4: 'Choice,',
                text4: '  you chose what games you want to your freespins on!',
            },
            we_not_like: 'We don\'t like:',
            secondList: {
                header1: '',
                test1: 'Wager requirements, so the money in your account are always yours. Just take them out if you want to.',
            },
            // bottomText: 'What are you waiting for? Just make your deposit and start playing!',
        },
        latest_games: 'Latest games',
        all_games: 'All games',
        popular_games: 'Popular games',
        subfooter: {
            general_info: {
                text1: 'Odin Services Limited',
                text2: 'Registration number C66002',
                text3: 'Registered address Level G (Office1/1665),',
                text4: 'Quantum House 75, Abate Rigord Street, Ta Xbiex XBX1120 Malta',
                text5: 'All our operations are regulated by the Maltese Gaming Authority.',
                text6: 'License number:  MGA/CL1/1253/2016 and MGA/CL1/1204/2016',
            },
            all_info: {
                all: 'Gaming can be both entertaining but for some it could also be addictive. To help you play responsible and, once logged in, we provide you with various mechanisms to set your own gaming limits, budgets and boundaries.       Through these you can limit your losses, the time spent on gambling or block you account. You can also contact a professional organization (such as GamCare,',
                after_link: 'or Gambling Therapy, ',
                end: ' ) for help.',
            },
        },
    },
    about_page: {
        header: 'About',
        first_text: 'At Fun88 Europe we pride ourselves in being an "instant casino experience" where game are available in one click and the account registration process is extremely simplified, whilst still more secure than with anyone else! Deposits and withdrawals are effected instant and we also provide customer support with a response time in less than 30 minutes.',
        second_text: 'Fun88 Europe is operated by Odin Service Limited under a license granted by the Malta Gaming Authority under the Remote Gaming Regulations.',
        odin_service: 'Odin Services Limited',
        registration_number: 'Registration number C66002',
        registered_address: 'Registered address Level G (Office1/1665), Quantum House 75, Abate Rigord Street, Ta Xbiex XBX1120 Malta',
        all_our_operations: 'All our operations are regulated by the Maltese Gaming Authority. ',
        license_number: 'License number: MGA/CL1/1253/2016 and MGA/CL1/1204/2016',
    },
    blockUser_page: {
        your_account_is_blocked: 'Your account is blocked',
        refund: ' We will send your money during 30 days',
        under_age: 'Your age is under 18 year old.',
    },
    createPassword_page: {
        thanks: 'Thanks for registration',
        generated_password: 'Now you can Sign in using email and password - ',
        create_new_password: 'Or you can create new password',
        create: 'Create',
        password_created: 'Password has been created.',
    },
    faq: {
        title: 'Frequently Asked Questions',
        header: 'Gaming can be both entertaining but for some it could also be addictive. To help you play responsible and, once logged in, we provide you with various mechanisms to set your own gaming limits, budgets and boundaries. If you have any questions on this, please don\'t hesitate to contact us and we\'ll be able to assist you.',
        questions: {
            question1: 'I\'m playing more than I should, how can you help me?',
            answer1: 'If you feel you\'re losing control or your gambling please use responsible gambling features available to you once logged in. Through these you can limit your losses, the time spent on gambling or even block you account. If you need assistance on this, please contact us and we\'ll be glad to help you. You can also contact a professional organization (such as GamCare, www.gamcare.org.uk or Gambling Therapy, www.gamblingtherapy.org) for help',
            question2: 'I have forgot my password, what should I do?',
            answer2: 'Either make a deposit and login using your bank credentials or contact our customer support to generate a new password.',
            question3: 'How can I find my game play history?',
            answer3: 'By contacting our customer support.',
            question4: 'Where can I find the rules of the games?',
            answer4: 'The rules of each game is available within the game after you\'ve opened it so simply click on the game you want to know the rules for and follow the links to the rules',
            question5: 'How do I register?',
            answer5: 'To secure your identity, and confirm your age as above 18, we only allow real money customers and you register by going through our deposit flow. We will collect the necessary information about you from your bank and let you select a password to finish the registration. The last step to begin playing is to verify your email address and we will send an email with a link for you to click on before game play can begin.',
        },
    },
    linked_account: {
        merged: 'Your accounts are merged!',
    },
    registration_deposit_page: {
        country: 'Country*',
        amount: 'Amount*',
        logo_text: 'All our payments are processed securely through Trustly. Both deposits and withdrawals are instantly available!',
        countries: {
            sweden: 'Sweden',
            poland: 'Poland',
            finland: 'Finland',
            austria: 'Austria',
            belgium: 'Belgium',
            bulgaria: 'Bulgaria',
            czech_republic: 'Czech Republic',
            estonia: 'Estonia',
            germany: 'Germany',
            hungary: 'Hungary',
            ireland: 'Ireland',
            italy: 'Italy', 
            latvia: 'Latvia', 
            lithuania: 'Lithuania',
            netherlands: 'Netherland', 
            romania: 'Romania', 
            slovakia: 'Slovakia', 
            slovenia: 'Slovenia',
            spain: 'Spain',
        },
        make_deposit: 'Make deposit',
        input_validation: 'Amount must be between 5 and 1.000.000',
        currency: 'Your current currency is EUR',
        header1: 'If you\'re a returning player you will automatically be logged in once the deposit is completed.',
        header2: 'If this is your first time here, just initiate the Trustly deposit flow by picking your country and entering what amount you want to deposit.',
        error: 'Enter a valid email.',
        wait: {
            first_text: 'Thanks for deposit',
            second_text: 'We are checking your status right now',
        },
    },
    reset_password: {
        header: 'Restore password',
        ok: 'Ok',
    },
    sign_in_page: {
        title: 'Sign in',
        login_with_email: 'Or login with Email',
        email: 'Email',
        email_placeholder: 'Email',
        cancel: 'Cancel',
        error: 'Enter a valid email.',
        password: 'Password:',
        password_placeholder: 'Password',
        sign_in: 'Sign in',
        set_exclusion: 'You\'ve set exclude. This limitation will expire in ',
        block_user: 'This user is blocked. ',
    },
    additional_info: {
        first_name: 'First name',
        last_name: 'Last name',
        street_address: 'Street address',
        zip_code: 'Zip code',
        city: 'City',
        gender: 'Gender',
        date_of_birth: 'Date of birth',
        required_fields: 'Required Fields',
        male: 'Male',
        female: 'Female',
    },
    card: {
        play: 'Play now',
        free_spins: 'Free spins!',
    },
    change_password: { 
        change_password: 'Change password',
        NEW_PASSWORD: 'NEW PASSWORD',
        CONFIRM_NEW_PASSWORD: 'CONFIRM NEW PASSWORD',
        password_changed: 'Password was changed.',
        password: 'PASSWORD',
        repeat_password: 'REPEAT PASSWORD',
    },
    mobile_version: 'Mobile version',
    my_account: 'My account',
    password_section: {
        password_must: 'Password must: ',
        minimum_characters: 'Be a minimum of 8 characters',
        include_at_least_one_number: 'Include at least one number',
        include_at_least_one_lowercase_letter: 'Include at least one lowercase letter (a-z)',
        include_at_least_one_uppercase_letter: 'Include at least one uppercase letter (A-Z) or include at least one special character',
    },
    trystly_login: {
        select_contry: 'Select country',
        continue_with_trustly: 'Continue with Trustly',
    },
    rewards: {
        title: 'FUN88 player\'s circle',
        first_text: 'Join FUN88 Player\'s circle rewards program to get free spins and take part in our prize draws! In order to join, all you have to do is make sure your email is verified and then just opt in! The reward program is of course free of charge and there are not wager requirements in order for you to with any of the bonuses or free spins you get.',
        second_text: 'And as if this wasn\'t enough you will also get 10 free spins just for joining so what are you waiting for?',
        turnonver: 'Your turnover since joining the program:',
        button: 'Join to circle',
        failed: 'Our rewards system has been turned off. Please, try again later.',
        thanks: 'Thank you for entering your campaign code. You\'ve now been given: "Lorem, ipsum, parum etc...."',
        campaing_code: 'Campaign code:',
        send: 'Send',
        joined_first_text: 'You\'re a part of our Player\'s Circle rewards program! We\'re glad to have you onboard!',
        joined_second_text: 'Some things for you to know:',
        item1: 'All winnings from free spins come with 0 wager requirements! What a bless, right?',
        item2: 'Each level have three games and your free spins are available on all three games. However, the number of free spins listed on each level is the total number of free spins you get for that level. So if a level have 25 free spins you will get 25 free spins in total. You can play 5 on one of the games, 10 on the second and another 10 on the third game. All all 25 at one game. Whatever you prefer!',
        item3: 'You need to game back to the rewards page to to click on a game on a level to receive the free spins for that level.',
        item4: 'The turnover is meant to be real time but in certain situations we might have a delay of a couple of minutes.',
        terms_conditions_title: 'Terms and Conditions',
        terms_conditions_1: 'The Player\'s Circle rewards are are intended for recreational players and we may, in our sole discretion, limit the eligibility of customers to participate at any time.',
        terms_conditions_2: 'The Player\'s Circle rewards are limited to one per person and/or email address. We reserve the right to withdraw the availability of any offer or all offers to any customer or group of customers at any time and at our sole and absolute discretion.',
        terms_conditions_3: 'We reserves the right to amend, cancel, reclaim or refuse any promotion, free spins or rewards at our own discretion at any time.',
        terms_conditions_4: 'We reserves the right to use your first name, city and country of residence in any announcements about any winnings once you\'ve joined the Player\'s Circle.',
        terms_conditions_5: 'We reserve the right to edit these Terms and Conditions at any time and will notify you via email if we do this.',
    },
    rewards_component: {
        level: 'Level',
        turnover: 'Turnover',
        free_spins: 'Free spins',
        games: 'Games',
        error: 'You can not join the circle until email is verified. ',
    },
}

module.exports = local_eng;